name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TIMEWEB_HOST }}
          username: ${{ secrets.TIMEWEB_LOGIN }}
          key: ${{ secrets.TIMEWEB_SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.TIMEWEB_LOGIN }}/langworld_db_pyramid
            
            # BOOTSTRAP: Update the code to the latest version
            git fetch origin master
            git reset --hard origin/master
            
            # Make sure the script is executable
            chmod +x ${{ secrets.TIMEWEB_RELPATH_TO_SCRIPT }}
            
            # Execute the (now updated) script
            ./${{ secrets.TIMEWEB_RELPATH_TO_SCRIPT }}
